# Task 2 Model Experimentation and Development - Global AI & Data Jobs Salary Dataset

## Objective

The purpose of this modelling task is to develop and evaluate a machine learning regression pipeline using PyCaret to predict the annual base salary of AI and data-related jobs.

The primary target variable is `salary_usd`. The modelling process will include preprocessing and transformation, model comparison using k-fold cross-validation, hyperparameter tuning, evaluation using multiple regression performance metrics, and selection of the best-performing model.

MLflow will also be used to track model experiments, metrics and artifacts throughout the model development process.

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

from hydra import compose, initialize

PROJECT_ROOT = Path.cwd().parents[1]

with initialize(version_base=None, config_path="../conf"):
    cfg = compose(config_name="config")

raw_data_path = PROJECT_ROOT / cfg.data.raw_path

df = pd.read_csv(raw_data_path)

print(f"Dataset shape: {df.shape}")
df.head()

Dataset shape: (90000, 35)

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,...,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,...,27,12,76,57,65,73,15,55,1.23,76
1,2,USA,AI Engineer,LLM,Entry,1,75507,11713,Bootcamp,Retail,...,27,54,29,69,60,51,15,58,0.87,67
2,3,Brazil,Research Scientist,Analytics,Entry,0,41660,5268,PhD,Healthcare,...,13,12,49,70,59,68,37,13,2.13,61
3,4,India,Software Engineer AI,Computer Vision,Senior,6,43268,7975,Diploma,Tech,...,30,80,47,79,65,55,46,74,1.49,56
4,5,Germany,Machine Learning Engineer,Computer Vision,Entry,0,69119,4758,Master,Retail,...,24,82,47,64,52,69,17,21,0.87,72

## 1. Modelling Preparation

The target variable for this regression task is `salary_usd`.

Before modelling, `id` is excluded because it is only a unique identifier. Based on the EDA and feature definitions, `bonus_usd` and `salary_percentile` are also excluded as potential target-leakage features, since they may contain salary-related information that would not be independently available when predicting a new job record.

All remaining predictors are initially retained, including features with weak individual relationships with salary, as they may still contribute through non-linear relationships or interactions.

The EDA also identified several preprocessing considerations. `experience_level` has a clear ordinal structure, while the treatment of `education_required` and `company_size` will be defined during preprocessing. Since most numerical predictors do not show substantial skewness, numerical feature transformation will not be applied by default.

A separate experiment will evaluate a transformed `salary_usd` target because the target distribution showed moderate positive skewness.

### 1.1 Reserve Unseen Data

Before model experimentation, 10% of the original dataset is randomly reserved as unseen data using a fixed random state for reproducibility. This produces **81,000 records for model development** and **9,000 records for final unseen prediction**.

The reserved unseen data will not be used during preprocessing experimentation, model comparison, cross-validation, hyperparameter tuning, or model selection. This ensures that it remains independent from the model development process and can be used to assess the final selected pipeline on previously unseen records.

The remaining 90% of the dataset is used for model development. PyCaret will subsequently perform an 80/20 train-holdout split on this development dataset, while 10-fold cross-validation is performed using the training portion.

In [2]:
from sklearn.model_selection import train_test_split

model_data, unseen_data = train_test_split(
    df,
    test_size=0.10,
    random_state=cfg.model.random_state
)

target = cfg.model.target

# Features excluded due to identifier / potential target leakage
ignore_features = [
    "salary_percentile",
    "bonus_usd",
    "id"
]

print(f"Target variable: {target}")
print(f"Features excluded from modelling: {ignore_features}")
print(f"Original dataset shape: {df.shape}")
print("Model development data:", model_data.shape)
print("Reserved unseen data:", unseen_data.shape)

Target variable: salary_usd
Features excluded from modelling: ['salary_percentile', 'bonus_usd', 'id']
Original dataset shape: (90000, 35)
Model development data: (81000, 35)
Reserved unseen data: (9000, 35)

## 2. Experiment 1 - Baseline Models with All Non-Leakage Candidate Features

The first experiment establishes a baseline using all remaining candidate predictors after excluding `id` and the potential target-leakage features `bonus_usd` and `salary_percentile`.

Basic preprocessing required to represent the data appropriately is applied. Based on the feature definitions identified during EDA, `experience_level`, `education_required`, and `company_size` are treated as ordinal categorical features using explicitly defined category orderings. The remaining categorical variables are handled using PyCaret's standard categorical preprocessing.

The original `salary_usd` target is used without target transformation, automated feature selection, additional feature engineering, or optional numerical transformation. This provides a controlled baseline against which subsequent modelling experiments can be compared.

Later experiments will investigate whether techniques such as automated feature selection, feature engineering, alternative preprocessing strategies, and target transformation improve model performance.

In [4]:
import os
import mlflow

os.environ["GIT_PYTHON_REFRESH"] = "quiet" # does not complain about GIT login 
mlflow.set_tracking_uri("http://127.0.0.1:5000")

### 2.1 Initialise Baseline PyCaret Experiment

The baseline PyCaret regression experiment is initialised using an 80/20 train-holdout split with 10-fold cross-validation.

`id`, `bonus_usd`, and `salary_percentile` are excluded, while all remaining candidate predictors are retained. Based on the EDA, `experience_level`, `education_required`, and `company_size` are treated as ordinal features using predefined category orderings, while PyCaret handles the remaining categorical preprocessing automatically.

During 10-fold cross-validation, the training data is divided into 10 subsets. The model is trained on 9 folds and validated on the remaining fold, repeating this process until every fold has been used for validation. The average performance across the folds provides a more reliable estimate of model performance than relying on a single train-validation split.

No automated feature selection, feature engineering, numerical transformation, or target transformation is applied in this baseline experiment. A fixed random state ensures reproducibility, while MLflow is enabled to track experiment results.

In [5]:
from pycaret.regression import RegressionExperiment

ordinal_features = {
    "experience_level": [
        "Entry",
        "Mid",
        "Senior",
        "Lead"
    ],

    "education_required": [
        "Bootcamp",
        "Diploma",
        "Bachelor",
        "Master",
        "PhD"
    ],

    "company_size": [
        "Startup",
        "Small",
        "Medium",
        "Large",
        "Enterprise"
    ]
}

categorical_features = [
    "country",
    "job_role",
    "ai_specialization",
    "industry",
    "work_mode"
]

baseline_exp = RegressionExperiment()

baseline_exp.setup(
    data=model_data,
    target=target,
    ignore_features=ignore_features,
    ordinal_features=ordinal_features,
    categorical_features=categorical_features,
    train_size=1 - cfg.training.test_size,
    fold_strategy="kfold",
    fold=cfg.training.fold,
    fold_shuffle=True,
    session_id=cfg.model.random_state,
    log_experiment="mlflow",
    experiment_name="salary_baseline_non_leakage"
)

2026/08/20 22:22:24 INFO mlflow.tracking.fluent: Experiment with name 'salary_baseline_non_leakage' does not exist. Creating a new experiment.

### 2.2 Baseline Model Comparison

Multiple regression algorithms are trained and evaluated using the same preprocessing pipeline and 10-fold cross-validation strategy defined in the baseline experiment.

The models are compared using MAE, MSE, RMSE, R², RMSLE, and MAPE. Among these metrics, `RMSE` is used as the primary metric for model comparison because it measures prediction error in the same USD scale as `salary_usd` while penalising larger errors more heavily than MAE. This is useful for salary prediction because the target contains legitimate high-salary observations, where large prediction errors would be particularly undesirable.

The remaining metrics are still considered to provide a broader assessment of model performance. MAE provides a more robust view of typical absolute error, while R² indicates the proportion of salary variation explained by the model.

The top-performing models are retained as candidates for subsequent modelling experiments and later hyperparameter tuning.

In [6]:
baseline_models = baseline_exp.compare_models(
    n_select=3,
    sort="RMSE"
)

2026/08/20 22:28:57 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:28:58 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Regressor at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/01853ea89ed642859f3817899a308352.
2026/08/20 22:28:58 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:21 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Regressor at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/b61c31bf8bef45bdb9fdb0f87e6501da.
2026/08/20 22:29:21 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:42 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Regressor at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/6b6f0a530c484c13b433f1506ef37950.
2026/08/20 22:29:42 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:43 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Regressor at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/7dbb0f19585741069efb0c55e9da9168.
2026/08/20 22:29:43 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:43 INFO mlflow.tracking._tracking_service.client: 🏃 View run Lasso Regression at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/0589df4323184e79848c674efad23360.
2026/08/20 22:29:43 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:44 INFO mlflow.tracking._tracking_service.client: 🏃 View run Lasso Least Angle Regression at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/a306ebe2a9524a8cb35940646874f4df.
2026/08/20 22:29:44 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:45 INFO mlflow.tracking._tracking_service.client: 🏃 View run Bayesian Ridge at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/64b4722399da44f3bb3cb7c039298652.
2026/08/20 22:29:45 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:45 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:45 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Regression at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/25fd82f2c2564db282405485715e36fd.
2026/08/20 22:29:45 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Regression at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/2cda9a468660483baebeff5b084c0c9d.
2026/08/20 22:29:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Regressor at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/63507c457e104d65a3c5a9d63073c806.
2026/08/20 22:29:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run AdaBoost Regressor at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/8b1bb89819304cd0be13e8a1abcbc12a.
2026/08/20 22:29:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run Elastic Net at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/c30606eda27d4713ac72ecc3e5692fc5.
2026/08/20 22:29:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:48 INFO mlflow.tracking._tracking_service.client: 🏃 View run Orthogonal Matching Pursuit at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/0b9d8301c77a47039ec0dea7b556930f.
2026/08/20 22:29:48 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:49 INFO mlflow.tracking._tracking_service.client: 🏃 View run Huber Regressor at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/e3a69dff2646439ba4ab9f4056070c93.
2026/08/20 22:29:49 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:49 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Regressor at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/aa2af112e58c4bd29e5ef6e97d5a143f.
2026/08/20 22:29:49 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:50 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:50 INFO mlflow.tracking._tracking_service.client: 🏃 View run Passive Aggressive Regressor at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/d3f070f226b448bd95ffb927fb501c00.
2026/08/20 22:29:50 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:50 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:50 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Regressor at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/0107873c022d49af98bd18d5a080b4ae.
2026/08/20 22:29:50 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.
2026/08/20 22:29:51 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:29:51 INFO mlflow.tracking._tracking_service.client: 🏃 View run Least Angle Regression at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/69cf1f546c74481da2c9c99d246b5a6f.
2026/08/20 22:29:51 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.

### 2.3 Baseline Model Comparison Results

The baseline comparison shows that ensemble tree-based models perform best under 10-fold cross-validation. CatBoost achieved the lowest RMSE of approximately **$11,309.14**, the lowest MAE of **$8,880.60**, and the highest R² of **0.9336**, making it the strongest baseline model according to the primary ranking metric.

Gradient Boosting ranked second with an RMSE of approximately **$11,773.73** and R² of **0.9280**, while Random Forest ranked third with an RMSE of **$11,825.28** and R² of **0.9274**.

These ensemble models substantially outperform the regularised linear models, which achieved RMSE values of approximately **$14,421** and R² values of around **0.8920**. This suggests that non-linear relationships and interactions between predictors provide useful information for salary prediction.

CatBoost, Gradient Boosting, and Random Forest will therefore be retained as the strongest baseline candidates for comparison with the subsequent modelling experiments.

In [7]:
baseline_results = baseline_exp.pull()

baseline_results.style.format({
    "MAE": "{:,.2f}",
    "MSE": "{:,.2f}",
    "RMSE": "{:,.2f}",
    "R2": "{:.4f}",
    "RMSLE": "{:.4f}",
    "MAPE": "{:.4f}",
    "TT (Sec)": "{:.3f}"
})

## 3. Experiment 2 - EDA-Guided Feature Selection and Feature Engineering

The second experiment evaluates whether reducing redundant or weakly informative predictors and combining closely related features can improve model performance.

Based on the EDA, `job_security_score` and `layoff_risk` are strongly related and represent similar aspects of employment stability. These two variables are replaced with a single engineered `employment_stability_score` to reduce redundancy while preserving their underlying information. In addition, `work_life_balance_score` (EDA 6.2) and `year` (EDA 7.3) are removed because the EDA suggested limited additional contribution relative to related predictors.

The remaining predictors are retained, including variables with weak individual correlations, as they may still contribute through non-linear relationships or interactions.

The same train-holdout split, 10-fold cross-validation strategy, preprocessing approach, and original `salary_usd` target are retained so that the effect of these feature refinements can be compared fairly against the baseline experiment.

The `employment_stability_score` combines `job_security_score` with the inverse of `layoff_risk` so that both components follow the same direction, where a higher value represents greater employment stability.

For example, if a job has a `job_security_score` of **80** and a `layoff_risk` of **0.20**, the layoff risk is first inverted and converted to a 0-100 scale:

`(1 - 0.20) × 100 = 80`

The two values are then averaged:

`(80 + 80) / 2 = 80`

The resulting `employment_stability_score` is **80**.

In [8]:
# Create Experiment 2 dataset
feature_data = model_data.copy()

# Engineer a combined employment stability feature
feature_data["employment_stability_score"] = (
    feature_data["job_security_score"]
    + (1 - feature_data["layoff_risk"]) * 100
) / 2

# Features removed based on EDA findings
manual_removed_features = [
    "job_security_score",
    "layoff_risk",
    "work_life_balance_score",
    "year"
]

feature_data.drop(
    columns=manual_removed_features,
    inplace=True
)

print("Baseline excluded features:", ignore_features)
print("Additional removed features:", manual_removed_features)
print("Engineered feature: employment_stability_score")
print("Experiment 2 dataset shape:", feature_data.shape)

Baseline excluded features: ['salary_percentile', 'bonus_usd', 'id']
Additional removed features: ['job_security_score', 'layoff_risk', 'work_life_balance_score', 'year']
Engineered feature: employment_stability_score
Experiment 2 dataset shape: (81000, 32)

### 3.1 Initialise Feature Selection PyCaret Experiment

In [9]:
feature_selection_exp = RegressionExperiment()

feature_selection_exp.setup(
    data=feature_data,
    target=target,
    ignore_features=ignore_features,
    ordinal_features=ordinal_features,
    categorical_features=categorical_features,
    train_size=1 - cfg.training.test_size,
    fold_strategy="kfold",
    fold=cfg.training.fold,
    fold_shuffle=True,
    session_id=cfg.model.random_state,
    log_experiment="mlflow",
    experiment_name="salary_feature_selection"
)

2026/08/20 22:31:19 INFO mlflow.tracking.fluent: Experiment with name 'salary_feature_selection' does not exist. Creating a new experiment.

### 3.2 Feature Selection Model Comparison

In [10]:
feature_selection_models = feature_selection_exp.compare_models(
    n_select=3,
    sort="RMSE"
)

Initiated  . . . . . . . . . . . . . . . . . .              22:31:23
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

2026/08/20 22:38:17 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:38:17 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Regressor at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/2eeae577d3a84b7bbc64a3381f523ba4.
2026/08/20 22:38:17 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:38:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:38:39 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Regressor at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/ec2ad439163b4641b741fadd854dc01f.
2026/08/20 22:38:39 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:38:54 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:02 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Regressor at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/ee23c26c9f7140a7a0bbaedba3bf3e5c.
2026/08/20 22:39:02 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:03 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:03 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Regressor at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/22da747ee4074c07a16189fc67d8dc84.
2026/08/20 22:39:03 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:03 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:03 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Regression at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/368db6b97ca94e8696c406f664089ac6.
2026/08/20 22:39:03 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:04 INFO mlflow.tracking._tracking_service.client: 🏃 View run Lasso Least Angle Regression at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/98bf7262d89f4474839660ac4704fc77.
2026/08/20 22:39:04 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:04 INFO mlflow.tracking._tracking_service.client: 🏃 View run Lasso Regression at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/4a8c7ac42c744fcb8e44c52249fb3068.
2026/08/20 22:39:04 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:05 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Regression at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/b48bc304b30848bc90c1537b91091ce8.
2026/08/20 22:39:05 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:05 INFO mlflow.tracking._tracking_service.client: 🏃 View run Bayesian Ridge at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/81a71c49756948f4a7349464289aa847.
2026/08/20 22:39:05 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:06 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Regressor at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/8c51172462b34bbb9dae58d13a845d2e.
2026/08/20 22:39:06 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:07 INFO mlflow.tracking._tracking_service.client: 🏃 View run Passive Aggressive Regressor at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/8da2c9b75eab4d5a96fd236723a20969.
2026/08/20 22:39:07 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:07 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:07 INFO mlflow.tracking._tracking_service.client: 🏃 View run AdaBoost Regressor at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/5b8961188cbe49fea896d7e3d742be90.
2026/08/20 22:39:07 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:07 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:08 INFO mlflow.tracking._tracking_service.client: 🏃 View run Orthogonal Matching Pursuit at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/3f6bbb9de4de44c89208dc99ae17e2d7.
2026/08/20 22:39:08 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:08 INFO mlflow.tracking._tracking_service.client: 🏃 View run Huber Regressor at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/59ca738f22b641aca851fa256c499a17.
2026/08/20 22:39:08 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:09 INFO mlflow.tracking._tracking_service.client: 🏃 View run Elastic Net at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/c3d95d6f20744a38b9be37bb65e4c41c.
2026/08/20 22:39:09 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:09 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Regressor at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/da583c5bd57447bfb53d2dba9f4c414a.
2026/08/20 22:39:09 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:10 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:10 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Regressor at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/4492ad2bb93842e7b8dd69b70162ab94.
2026/08/20 22:39:10 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.
2026/08/20 22:39:10 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 22:39:11 INFO mlflow.tracking._tracking_service.client: 🏃 View run Least Angle Regression at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/14615fe2b81f48bc8ff9e2ebc7e899ef.
2026/08/20 22:39:11 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.

### 3.3 Feature Selection and Engineering Model Comparison Results

The feature-refined experiment produced similar performance to the baseline, with CatBoost, Gradient Boosting, and Random Forest remaining the three strongest models. CatBoost achieved the lowest RMSE of approximately **$11,328.89**, followed by Gradient Boosting at **$11,807.94** and Random Forest at **$11,843.74**.

However, all three models performed slightly worse than their corresponding baseline results. CatBoost's RMSE increased from **$11,309.14 to $11,328.89**, Gradient Boosting from **$11,773.73 to $11,807.94**, and Random Forest from **$11,825.28 to $11,843.74**. Their MAE and R² values also showed small deteriorations.

This suggests that replacing `job_security_score` and `layoff_risk` with the engineered `employment_stability_score`, together with removing `work_life_balance_score` and `year`, resulted in a small loss of predictive information. Therefore, the original baseline feature configuration will be restored for **Experiment 3**, which evaluates whether normalisation and target transformation improve model performance.

In [11]:
feature_selection_results = feature_selection_exp.pull()

feature_selection_results.style.format({
    "MAE": "{:,.2f}",
    "MSE": "{:,.2f}",
    "RMSE": "{:,.2f}",
    "R2": "{:.4f}",
    "RMSLE": "{:.4f}",
    "MAPE": "{:.4f}",
    "TT (Sec)": "{:.3f}"
})

## 4. Experiment 3 - Normalisation and Target Transformation

The third experiment evaluates whether additional preprocessing can improve model performance. Since Experiment 2 produced slightly weaker results, the original baseline feature configuration from Experiment 1 is restored.

Min-Max normalisation is applied to the numerical predictors to place them on a common scale. Although the EDA did not identify feature scaling as a specific requirement, normalisation is evaluated as an additional preprocessing step to determine whether scale-sensitive models benefit from having numerical variables represented on a consistent range.

In addition, a Yeo-Johnson transformation is applied to the `salary_usd` target because the EDA identified moderate positive skewness in its distribution. This transformation aims to reduce the skewness of the target and lessen the influence of very high salary values during model training.

The same train-holdout split, 10-fold cross-validation strategy, and random state are retained to ensure that the results can be compared fairly with the previous experiments.

### 4.1 Initialise Normalisation and Target Transformation PyCaret Experiment

In [12]:
preprocessing_exp = RegressionExperiment()

preprocessing_exp.setup(
    data=model_data,
    target=target,
    ignore_features=ignore_features,
    ordinal_features=ordinal_features,
    categorical_features=categorical_features,

    normalize=True,
    normalize_method="minmax",

    transform_target=True,

    train_size=1 - cfg.training.test_size,
    fold_strategy="kfold",
    fold=cfg.training.fold,
    fold_shuffle=True,
    session_id=cfg.model.random_state,

    log_experiment="mlflow",
    experiment_name="salary_normalization_target_transform"
)

2026/08/20 23:52:40 INFO mlflow.tracking.fluent: Experiment with name 'salary_normalization_target_transform' does not exist. Creating a new experiment.

### 4.2 Normalisation and Target Transformation Model Comparison

In [13]:
preprocessing_models = preprocessing_exp.compare_models(
    n_select=3,
    sort="RMSE"
)

2026/08/20 23:59:34 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:34 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Regressor at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/7502b7150b394c9c9f5f2a9318f9f480.
2026/08/20 23:59:34 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:39 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:39 INFO mlflow.tracking._tracking_service.client: 🏃 View run Huber Regressor at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/ed91fa55edac4b348abc1ac58467579d.
2026/08/20 23:59:39 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:41 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Regression at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/fd9c5fc9c54040c193d3d50f8e351bee.
2026/08/20 23:59:41 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:41 INFO mlflow.tracking._tracking_service.client: 🏃 View run Bayesian Ridge at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/6e67bea6cf774ca4b00e9c5e293d98c0.
2026/08/20 23:59:41 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:42 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Regression at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/e36ad5031aaa49dda2cb03b177d080cc.
2026/08/20 23:59:42 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:43 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Regressor at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/70a869cf6aab4ce0933f798718656697.
2026/08/20 23:59:43 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:43 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Regressor at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/91fcb3ac94fc44348d59dc81f5650921.
2026/08/20 23:59:43 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:44 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Regressor at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/128ff3bc9c644e938b2554d4ccf39e70.
2026/08/20 23:59:44 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:44 INFO mlflow.tracking._tracking_service.client: 🏃 View run AdaBoost Regressor at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/e37a4ffbf24d42ef8cac74d7d27d3d12.
2026/08/20 23:59:44 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:45 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:45 INFO mlflow.tracking._tracking_service.client: 🏃 View run Passive Aggressive Regressor at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/720a414728a84fc2b36a7b38ea855d1a.
2026/08/20 23:59:45 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:45 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Regressor at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/e54eeb7296aa4378bd03973782ba6448.
2026/08/20 23:59:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run Orthogonal Matching Pursuit at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/56db968088bf4914a284f834f2cd3d17.
2026/08/20 23:59:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Regressor at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/4503aead6c6e4bbba0ae94b569c724ca.
2026/08/20 23:59:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run Lasso Least Angle Regression at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/114e587e0a474a458288e8c022467d27.
2026/08/20 23:59:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:48 INFO mlflow.tracking._tracking_service.client: 🏃 View run Lasso Regression at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/70b1bcbf9fcc453f8e2dddf022c7d83a.
2026/08/20 23:59:48 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:48 INFO mlflow.tracking._tracking_service.client: 🏃 View run Elastic Net at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/61ee18e78f0644309919f86911c35ef9.
2026/08/20 23:59:48 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:49 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Regressor at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/e68b731349da4a8d82655f16766f64ea.
2026/08/20 23:59:49 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.
2026/08/20 23:59:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/20 23:59:50 INFO mlflow.tracking._tracking_service.client: 🏃 View run Least Angle Regression at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/818647a1320c4521911336abe594433b.
2026/08/20 23:59:50 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.

### 4.2 Normalisation and Target Transformation Model Comparison Results

Under the normalisation and target-transformation configuration, CatBoost achieved the strongest performance with the lowest RMSE of approximately **$11,268.07**, the lowest MAE of **$8,851.79**, and the highest R² of **0.9341**.

Huber Regressor ranked second with an RMSE of approximately **$11,649.09** and R² of **0.9296**, while Linear Regression ranked third with an RMSE of approximately **$11,666.72** and R² of **0.9293**. 

The results also show that the additional preprocessing changes the relative performance of several algorithms, with Huber Regressor and Linear Regression performing considerably more competitively under this configuration.

In [14]:
preprocessing_results = preprocessing_exp.pull()

preprocessing_results.style.format({
    "MAE": "{:,.2f}",
    "MSE": "{:,.2f}",
    "RMSE": "{:,.2f}",
    "R2": "{:.4f}",
    "RMSLE": "{:.4f}",
    "MAPE": "{:.4f}",
    "TT (Sec)": "{:.3f}"
})

## 5. Experiment Comparison and Selection of Final Modelling Setup

The top three models from each experiment are compared using the same evaluation metrics obtained from 10-fold cross-validation. RMSE remains the primary comparison metric, while MAE and R² are also considered when selecting the modelling configuration to carry forward for hyperparameter tuning.

In [16]:
# Select top 3 models from each experiment based on RMSE
baseline_top3 = (
    baseline_results
    .nsmallest(3, "RMSE")
    .assign(Experiment="Experiment 1 - Baseline")
)

feature_selection_top3 = (
    feature_selection_results
    .nsmallest(3, "RMSE")
    .assign(Experiment="Experiment 2 - Feature Refinement")
)

preprocessing_top3 = (
    preprocessing_results
    .nsmallest(3, "RMSE")
    .assign(Experiment="Experiment 3 - Preprocessing")
)

# Combine results
experiment_comparison = (
    pd.concat(
        [
            baseline_top3,
            feature_selection_top3,
            preprocessing_top3
        ],
        ignore_index=True
    )
    [["Experiment", "Model", "MAE", "RMSE", "R2", "RMSLE", "MAPE"]]
    .sort_values("RMSE", ascending=True)
    .reset_index(drop=True)
)

experiment_comparison.style.format({
    "MAE": "${:,.2f}",
    "RMSE": "${:,.2f}",
    "R2": "{:.4f}",
    "RMSLE": "{:.4f}",
    "MAPE": "{:.4f}"
})

Across all experiments, CatBoost achieved the strongest performance. The best overall result was obtained in **Experiment 3 - Preprocessing**, where CatBoost achieved an RMSE of **$11,268.07**, MAE of **$8,851.79**, and R² of **0.9341**. This slightly outperformed CatBoost under the baseline configuration in Experiment 1, which achieved an RMSE of **$11,309.14**, and the feature-refined configuration in Experiment 2, which achieved an RMSE of **$11,328.89**.

Experiment 3 also improved the performance of several non-tree models. Huber Regressor and Linear Regression achieved RMSE values of **$11,649.09** and **$11,666.72** respectively, making them more competitive than under the previous configurations.

Based on the initial 10-fold cross-validation results, Experiment 3 currently provides the strongest modelling configuration, with CatBoost achieving the lowest RMSE of **$11,268.07**.

However, the CatBoost models from Experiments 1 and 2 also achieved competitive performance, so the three CatBoost configurations will be carried forward for hyperparameter tuning before selecting the final modelling pipeline.

## 6. Hyperparameter Tuning

Hyperparameter tuning is performed on the three strongest model configurations identified during the experiment comparison. All three use CatBoost but differ in their preprocessing pipelines:

- Experiment 1: Baseline preprocessing
- Experiment 2: Feature selection and engineering
- Experiment 3: Normalisation and target transformation

Each CatBoost model is tuned using the same cross-validation strategy and RMSE as the primary optimisation metric. The tuned results are then compared to determine the final model and preprocessing pipeline.

In [ ]:
baseline_catboost = baseline_exp.create_model(
    "catboost"
)

feature_catboost = feature_selection_exp.create_model(
    "catboost"
)

preprocessing_catboost = preprocessing_exp.create_model(
    "catboost"
)

2026/08/21 00:10:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 00:10:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Regressor at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/8160351bd1ec42928b6f352c7cfb088d.
2026/08/21 00:10:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.

2026/08/21 00:11:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 00:11:35 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Regressor at: http://127.0.0.1:5000/#/experiments/632020753518260600/runs/5fea0c22bc494988a9078460cb9ce46d.
2026/08/21 00:11:35 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/632020753518260600.

2026/08/21 00:12:17 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 00:12:17 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Regressor at: http://127.0.0.1:5000/#/experiments/450861933026043037/runs/0363557ca99e4bd48501f94538ef4bd8.
2026/08/21 00:12:17 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/450861933026043037.

In [22]:
catboost_grid = {
    "iterations": [300, 500, 700],
    "depth": [4, 6, 8],
    "learning_rate": [0.03, 0.05, 0.1],
    "l2_leaf_reg": [3, 5, 7],
    "random_strength": [1, 2]
}

tuned_baseline_catboost = baseline_exp.tune_model(
    baseline_catboost,
    custom_grid=catboost_grid,
    optimize="RMSE",
    n_iter=20,
    fold=10,
    choose_better=True
)

Fitting 10 folds for each of 20 candidates, totalling 200 fits

2026/08/21 01:07:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 01:07:04 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Regressor at: http://127.0.0.1:5000/#/experiments/675356573797874508/runs/1a561f3f71334f528446bb15933dddc3.
2026/08/21 01:07:04 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/675356573797874508.

In [ ]:
print("Experiment 1 tuned parameters:")
print(tuned_baseline_catboost.get_params())

print("\nExperiment 2 tuned parameters:")
print(tuned_feature_catboost.get_params())

print("\nExperiment 3 tuned parameters:")
print(tuned_preprocessing_catboost.get_params())

tuned_baseline_results = baseline_exp.pull()
tuned_feature_results = feature_selection_exp.pull()
tuned_preprocessing_results = preprocessing_exp.pull()